### ISSUE TITLE
Missing S3 buckets permission in YAML declaration

### ISSUE THREAD

**Issue by jungleBadger** [udacity/cd12101-lesson-demos-and-exercise-starters-solutions#166]
The [S3 bucket declaration](https://github.com/udacity/cd12101-lesson-demos-and-exercise-starters-solutions/blob/fa74b4816506bfe3fddd85e396ef03b620abb37f/lesson-3-events-processing/exercises/06-resize-s3-image-solution/backend/serverless.yml#L137) for the Attachments bucket in the following path [cd12101-lesson-demos-and-exercise-starters-solutions](https://github.com/udacity/cd12101-lesson-demos-and-exercise-starters-solutions/tree/main)/[lesson-3-events-processing](https://github.com/udacity/cd12101-lesson-demos-and-exercise-starters-solutions/tree/main/lesson-3-events-processing)/[exercises](https://github.com/udacity/cd12101-lesson-demos-and-exercise-starters-solutions/tree/main/lesson-3-events-processing/exercises)/[06-resize-s3-image-solution](https://github.com/udacity/cd12101-lesson-demos-and-exercise-starters-solutions/tree/main/lesson-3-events-processing/exercises/06-resize-s3-image-solution)/[backend](https://github.com/udacity/cd12101-lesson-demos-and-exercise-starters-solutions/tree/main/lesson-3-events-processing/exercises/06-resize-s3-image-solution/backend) and exercise onwards are missing the following declaration to avoid a permission error upon creation:

Here is the highlighted snippet and full resource declaration for reference:
![image](https://github.com/udacity/cd12101-lesson-demos-and-exercise-starters-solutions/assets/12788435/8a852bf5-f1ba-4eb0-9634-9a1e18a2a415)

```yaml
    AttachmentsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.IMAGES_S3_BUCKET}
        PublicAccessBlockConfiguration:
          BlockPublicPolicy: false
          RestrictPublicBuckets: false
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - DELETE
                - HEAD
              MaxAge: 3000
```
